//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ShaderEditor.rc
//
#define IDS_TOOMUCHSTAGE                1
#define IDS_CANNOTDELPROP               2
#define IDS_SAVEPROMPT                  3
#define IDR_MAINMENU                    104
#define IDD_SHADERFORM                  105
#define IDD_PROPERTYFORM                106
#define IDB_SELECTED                    108
#define IDB_UNSELECTED                  109
#define IDB_GENERAL                     110
#define IDB_TREELINE                    111
#define IDR_SHADERMENU                  115
#define IDR_GENERALMENU                 116
#define IDR_GENPROPMENU                 117
#define IDR_STAGEMENU                   118
#define IDR_STGPROPMENU                 119
#define IDR_STGPROPLISTMENU             120
#define IDD_COMBOLISTDLG                121
#define IDD_ALPHACOMPDLG                122
#define IDD_GENBLENDDLG                 123
#define IDD_TEXTUREDLG                  124
#define IDD_BUMPMATDLG                  125
#define IDD_SINGLEVALDLG                126
#define IDD_TEXOPDLG                    127
#define IDD_SAVEASKDLG                  128
#define IDD_NEWSDRDLG                   129
#define IDD_WAVEDLG                     130
#define IDD_TWOVALUEDLG                 131
#define IDR_TCMODMENU                   132
#define IDR_TCMODPROPMENU               133
#define IDB_TCMODS                      134
#define IDI_APPICON                     135
#define IDD_PIXELSHADERDLG              136
#define IDD_SELECTFILE                  137
#define IDD_COLORVALUE                  138
#define IDD_TEXCOORDINDEX               139
#define IDD_TEXTRANSFORM                140
#define IDD_COMBOVALDLG                 141
#define IDD_D3DTEXTURES                 142
#define IDC_SHADERLIST                  1000
#define IDC_TREE_DIRECTORY              1000
#define IDC_PROPTREE                    1001
#define IDC_LIST_FILE                   1001
#define IDC_VALUELIST                   1002
#define IDC_STATIC_PROMPT               1002
#define IDC_COMPCOMBO                   1003
#define IDC_REFVALUE                    1004
#define IDC_SRCBLENDCOMBO               1005
#define IDC_DESTBLENDCOMBO              1006
#define IDC_TEXTURELIST                 1006
#define IDC_TEXTYPELIST                 1007
#define IDC_TEXFILE                     1008
#define IDC_TEXFORMATLIST               1008
#define IDC_MAT00                       1009
#define IDC_MAT01                       1010
#define IDC_MAT10                       1011
#define IDC_MAT11                       1012
#define IDC_VALUE                       1013
#define IDC_PROMPT                      1014
#define IDC_OPCOMBO                     1015
#define IDC_ARGCOMBO1                   1016
#define IDC_MODCOMBO1                   1017
#define IDC_ARGCOMBO2                   1018
#define IDC_YESTOALL                    1018
#define IDC_MODCOMBO2                   1019
#define IDC_YES                         1019
#define IDC_NOT                         1020
#define IDC_NOTTOALL                    1021
#define IDC_NAME                        1024
#define IDC_BROWSE                      1025
#define IDC_FILE                        1026
#define IDC_WAVECOMBO                   1027
#define IDC_BASELINE                    1028
#define IDC_AMPLITUDE                   1029
#define IDC_PHASE                       1030
#define IDC_PERIOD                      1031
#define IDC_VALUEEDIT1                  1032
#define IDC_VALUE2                      1033
#define IDC_VALUEEDIT2                  1034
#define IDC_VALUE1                      1035
#define IDC_NUMFRAME                    1036
#define IDC_FRAMETIME                   1037
#define IDC_FILELIST                    1038
#define IDC_SHADERFILE                  1039
#define IDC_CONTENT                     1040
#define IDC_SAVE                        1041
#define IDC_COMPILE                     1042
#define IDC_USEPIXELSHADER              1044
#define IDC_EDIT_TEXTUREFILE            1045
#define IDC_BTN_BROWSE                  1046
#define IDC_EDIT_PIXELFILE              1047
#define IDC_EDIT_R                      1049
#define IDC_EDIT_G                      1050
#define IDC_EDIT_B                      1051
#define IDC_COMBO_INDEX                 1051
#define IDC_EDIT_A                      1052
#define IDC_COMBO_FLAGS                 1052
#define IDC_EDIT_M11                    1054
#define IDC_EDIT_M12                    1055
#define IDC_EDIT_M13                    1056
#define IDC_EDIT_M14                    1057
#define IDC_EDIT_M21                    1058
#define IDC_EDIT_M22                    1059
#define IDC_EDIT_M23                    1060
#define IDC_EDIT_M24                    1061
#define IDC_EDIT_M31                    1062
#define IDC_EDIT_M32                    1063
#define IDC_EDIT_M33                    1064
#define IDC_EDIT_M34                    1065
#define IDC_EDIT_M41                    1066
#define IDC_EDIT_M42                    1067
#define IDC_EDIT_M43                    1068
#define IDC_EDIT_M44                    1069
#define IDC_CHECK_PROJECTED             1070
#define IDC_COMBO_VALUE                 1071
#define IDC_STATIC_DESC                 1072
#define IDC_LIST_TEXTURES               1074
#define IDC_BTN_RESTORE                 1076
#define ID_FILE_EXIT                    40001
#define ID_SHADER_RENAME                40005
#define ID_SHADER_ADDSTAGE              40006
#define ID_SHADER_REMOVE                40007
#define ID_GEN_COPY                     40008
#define ID_GEN_PASTE                    40009
#define ID_GPROP_EDIT                   40010
#define ID_GPROP_REMOVE                 40011
#define ID_STG_HIDE                     40012
#define ID_STG_ADDBEFORE                40016
#define ID_STG_ADDAFTER                 40017
#define ID_STG_MOVEUP                   40018
#define ID_STG_MOVEDOWN                 40019
#define ID_STG_TEXTURE                  40020
#define ID_STG_REMOVE                   40021
#define ID_SPROP_EDIT                   40022
#define ID_SPROP_REMOVE                 40027
#define ID_GEN_ZCOMPARE                 40028
#define ID_GEN_ZENABLE                  40029
#define ID_GEN_ZWRITE                   40030
#define ID_GEN_ALPHACOMPARE             40031
#define ID_GEN_CULLMODE                 40033
#define ID_GEN_BLEND                    40034
#define ID_STG_COLOROP                  40036
#define ID_STG_ALPHAOP                  40037
#define ID_STG_BUMPMAT                  40038
#define ID_STG_BUMPSCALE                40039
#define ID_STG_BUMPOFFSET               40040
#define ID_STG_FILTER                   40041
#define ID_STG_ADDRESS                  40042
#define ID_SHADER_SAVE                  40043
#define ID_SHADER_SAVEAS                40044
#define ID_FILE_SETWORKPATH             40045
#define ID_FILE_SAVEALL                 40046
#define ID_GEN_COLORGEN                 40047
#define ID_GEN_ALPHAGEN                 40048
#define ID_STG_TCSCALE                  40049
#define ID_STG_TCSCROLL                 40050
#define ID_STG_TCROTATE                 40051
#define ID_STG_TCSTRETCH                40053
#define ID_TCMP_EDIT                    40054
#define ID_TCMP_REMOVE                  40055
#define ID_TCMP_MOVEUP                  40056
#define ID_TCMP_MOVEDOWN                40057
#define ID_STG_TCTURB                   40058
#define ID_GEN_PIXELSHADER              40059
#define ID_FILE_SETBACKCOL              40060
#define ID_STG_COPY                     40061
#define ID_STG_CUT                      40062
#define ID_STG_PASTE                    40063
#define ID_SHADER_COPY                  40064
#define ID_SHADER_PASTE                 40065
#define ID_OPT_BGCOLOR                  40066
#define ID_OPT_BGTEXTURE                40067
#define ID_OPT_VERTCOLOR                40068
#define ID_STG_RESULTARG                40069
#define ID_GEN_TFACTOR                  40071
#define ID_STG_TEXCOORD                 40072
#define ID_STG_TEXTRANSFORM             40073
#define ID_GEN_ALPHATEX                 40074
#define ID_OPT_D3DTEXTURE               40075
#define ID_GEN_PSC2                     40076
#define ID_GEN_PSC3                     40077
#define ID_GEN_PSC4                     40078
#define ID_GEN_PSC5                     40079
#define ID_GEN_PSC6                     40080
#define ID_GEN_PSC7                     40081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40082
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
